CREATE TABLE ISSUESLIST
(
ID SERIAL PRIMARY KEY,
NAME VARCHAR(30)
);


CREATE TABLE ISSUES
(
ID SERIAL PRIMARY KEY,
ISSUESLIST_ID BIGINT UNSIGNED NOT NULL,
SUMMARY VARCHAR(50) NOT NULL,
`DESCRIPTION` VARCHAR(500),
USER_ID_ASSIGNEDTO BIGINT UNSIGNED NOT NULL,
FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLIST(ID),
FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS(ID)
);


INSERT INTO ISSUESLIST (ID, `NAME`)
VALUES (1, "ToDo");

INSERT INTO ISSUESLIST (ID, `NAME`)
VALUES (2, "InProgress");

INSERT INTO ISSUESLIST (ID, `NAME`)
VALUES (3, "Done");


INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (1, 1, "Issue 1", "Do Issue 1........", 2);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (2, 1, "Issue 2", "Do Issue 2........", 1);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (3, 1, "Issue 3", "Do Issue 3........", 3);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (4, 1, "Issue 4", "Do Issue 4........", 2);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (5, 1, "Issue 5", "Do Issue 5........", 2);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (6, 1, "Issue 6", "Do Issue 6........", 2);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (7, 2, "Issue 7", "Doing Issue 7........", 5);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (8, 2, "Issue 8", "Doing Issue 8........", 5);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (9, 2, "Issue 9", "Doing Issue 9........", 5);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (10, 2, "Issue 10", "Doing Issue 10........", 1);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (11, 2, "Issue 11", "Doing Issue 11........", 2);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (12, 2, "Issue 12", "Doing Issue 12........", 4);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (13, 3, "Issue 13", "Done Issue 13........", 5);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (14, 3, "Issue 14", "Done Issue 14........", 5);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (15, 3, "Issue 15", "Done Issue 15........", 4);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (16, 3, "Issue 16", "Done Issue 16........", 4);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (17, 3, "Issue 17", "Done Issue 17........", 4);

INSERT INTO ISSUES (ID, ISSUESLIST_ID, SUMMARY, `DESCRIPTION`, USER_ID_ASSIGNEDTO)
VALUES (18, 3, "Issue 18", "Done Issue 18........", 2);


COMMIT;



//printing
SELECT  I.ID, I.SUMMARY, IL.NAME
FROM ISSUESLIST IL
JOIN ISSUES I ON IL.ID = I.ISSUESLIST_ID;

SELECT  I.ID, I.SUMMARY, U.FIRSTNAME, U.LASTNAME
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
GROUP BY I.ID;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS ISSUES_COUNT
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
GROUP BY USER_ID_ASSIGNEDTO;
