
CREATE TABLE BOOKS_AUD (
  EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
  EVENT_DATE DATETIME NOT NULL,
  EVENT_TYPE VARCHAR(10) DEFAULT NULL,
  BOOK_ID INT(11),
  OLD_TITLE VARCHAR(30),
  NEW_TITLE VARCHAR(30),
  OLD_PUBYEAR INT(4),
  NEW_PUBYEAR INT(4),
  PRIMARY KEY (`EVENT_ID`)
  );


DELIMITER $$
CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS
FOR EACH ROW
BEGIN
	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR)
		VALUES(curtime(), "INSERT", NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR);
END $$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS
FOR EACH ROW
BEGIN
	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID)
		VALUES(curtime(), "DELETE", OLD.BOOK_ID);
END $$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS
FOR EACH ROW
BEGIN
	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR, OLD_TITLE, OLD_PUBYEAR)
		VALUES(curtime(), "UPDATE", OLD.BOOK_ID, NEW.TITLE, NEW.PUBYEAR, OLD.TITLE, OLD.PUBYEAR);
END $$
DELIMITER ;
