CREATE TABLE `STATS`
(
    STAT_ID   INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STAT      VARCHAR(20) NOT NULL DEFAULT 'STATISTIC',
    `VALUE`   INT(11)     NOT NULL DEFAULT 0
);


CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(BESTSELLERS)
FROM BOOKS;


DROP FUNCTION IF EXISTS GetAllBestsellersQuantity;
DELIMITER $$
CREATE FUNCTION GetAllBestsellersQuantity() RETURNS INT DETERMINISTIC
BEGIN
    DECLARE BESTSELLERS_QUANTITY INT;
    SELECT `COUNT(BESTSELLERS)`
    FROM BESTSELLERS_COUNT
    INTO BESTSELLERS_QUANTITY;
    RETURN BESTSELLERS_QUANTITY;
END $$
DELIMITER ;


USE KODILLA_COURSE;
CREATE EVENT UPDATE_BESTSELLERS_WITH_COUNT
    ON SCHEDULE EVERY 1 MINUTE
    DO CALL UpdateBestsellers();
INSERT INTO `STATS` (STAT, `VALUE`)
VALUES ("BESTSELLERS QUANTITY", GetAllBestsellersQuantity());

COMMIT;