DROP PROCEDURE IF EXISTS QUERY_PLAN;
DELIMITER $$
CREATE PROCEDURE QUERY_PLAN()
BEGIN
    EXPLAIN
    SELECT FIRSTNAME
    FROM READERS
    WHERE FIRSTNAME = "John";
END $$
DELIMITER ;

CALL QUERY_PLAN();

CREATE INDEX BOOKS_TITLE ON BOOKS (TITLE);
CREATE INDEX READERS_DATA ON READERS (FIRSTNAME, LASTNAME);

CALL QUERY_PLAN();
 